### ISSUE TITLE
Total collateralization calculation with multi-collateral

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc#221]
We have an RPC that returns the total system collateralization. The function is not called by the parachain itself. We need to decide how we want to calculate the collateralization.

- Calculate the total across all currencies. However, since each currency potentially has different secure thresholds, the value is meaningless.
- Calculate the total across all currencies, but scale by secure threshold. E.g.` (to_btc(total_DOT) / secure_threshold(total_DOT) +to_btc(total_KSM) / secure_threshold(total_KSM)) / total_INTERBTC`. This gives a meaningful value - a value > 1.0 is good. But for users it might be confusing, since they expect overcollateralization. Maybe for users a collateral utilization percentage would be easier to understand, i.e. a value of 0 - 100%, where 100% means we are at the capacity limit
- Instead of a single value, return a `Vec<(CurrencyId, UnsignedFixedPoint)>` and let the UI figure out how to display and aggregate it.

I think I'm leaning towards the last solution for greatest flexibility.

**Comment by nud3l** [comment]
> Instead of a single value, return a Vec<(CurrencyId, UnsignedFixedPoint)> and let the UI figure out how to display and aggregate it.

What is the returned fixed point there?

I am also leaning towards implementing this on the lib level rather than on the parachain. The RPC calls have proven to be not the greatest for UI optimization but rather we should go for a caching layer. So my suggestion would be:
1. Remove this RPC from the parachain
2. Implement a function on the lib that reflects the system collateralization. (cc @savudani8 @theodorebugnet). For the lib function, my suggestion would be two-fold:

- on the user facing side (dashboard, list of vaults) -> show a weighted aggregate of the collateralization: `collateralization = (to_btc(ksm) * issued_interbtc_from_ksm + to_btc(dot) * issued_interbtc_from_dot) / total_issued_interbtc`
- on the vault facing side (vault dashboard) -> show collateralization per collateral asset: `collateralization(asset) = to_btc(asset)/interbtc_from_asset`

**Comment by gregdhill** [comment]
The returned value would be `(total_collateral / exchange_rate) / issued_tokens` as it is now but for each currency. I agree that this can / should be removed in favour of something more performant on the caching layer.

@sander2 I think this would allow us to remove the `TotalUserVaultCollateral` storage item as well.

**Comment by nud3l** [comment]
The only thing that might prove tricky in the caching layer is how to figure out how many tokens are issued from which collateral asset. Do we have that on-chain available other than iterating over all vaults and figuring out their collateral currency and issued_tokens?

**Comment by nud3l** [comment]
Closing this issue. It doesn't make sense to calculate a total collateralization level for the system.
