### ISSUE TITLE
Can we remove the UnauthorizedRedeemer error?

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc#559]
**Is your feature request related to a problem? Please describe.**
If the merkle proof and transaction is valid, why do we limit who can cancel a redeem request?

**Describe the solution you'd like**
Remove the requirement on `cancel_redeem`.

**Comment by nud3l** [comment]
> If the merkle proof and transaction is valid

On cancel redeem, there is no merkle proof. Not sure if you refer to another function?

> why do we limit who can cancel a redeem request?

No other entity other than the user can decide if they want to be reimbursed or retry. If we open cancel_redeem to anyone, we open frontrunning that decision by Vaults and other parties.  So that is not a change that should be made.

**Comment by gregdhill** [comment]
Yeah this was a stupid issue, not sure why I made it in hindsight. I think I was conflating `execute_redeem` with `cancel_redeem`.
